### ISSUE TITLE
Roadmap to unify confidential images and use KBS URI mechinism

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/guest-components#191]
This road map tracks the issue mentioned in https://github.com/confidential-containers/attestation-agent/issues/113 and https://github.com/confidential-containers/documentation/issues/85.

#### Stage 1

- [x] Have a universal format of `AnnotationPacket`
https://github.com/confidential-containers/attestation-agent/pull/117
- [x] Introduce KBS URI scheme & implement cc-kbc, sample-kbc, offline-fs-kbc, offline-sev-kbc, online-sev-kbc, eaa-kbc
https://github.com/confidential-containers/attestation-agent/pull/129
- [ ] simple-kbs for kbs uri
https://github.com/confidential-containers/simple-kbs/issues/57
- [x] verdictd side (eaa-kbc related) for kbs uri
https://github.com/inclavare-containers/verdictd/issues/29
- [x] implement on the image-rs side to use the new `get_rersource` API
https://github.com/confidential-containers/image-rs/issues/116
- [x] implement a single key-provider to follow the new spec
https://github.com/confidential-containers/attestation-agent/pull/143
- [x] ci fix for kata-cc 
- [x] ci fix for enclave-cc
https://github.com/confidential-containers/enclave-cc/issues/108

This road map tracks the issue mentioned in https://github.com/confidential-containers/attestation-agent/issues/113 and https://github.com/confidential-containers/documentation/issues/85.
