### ISSUE TITLE
Roadmap to support Sealed Secret

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/guest-components#295]
Sealed Secret was proposed in https://github.com/confidential-containers/confidential-containers/issues/136. This issue is used to track the development of sealed secret.

CDH:
- [x] Define the format of sealed secret
- [x] Impl the UnsealSecret API in Confidential DataHub
- [x] Tool to generate sealed secret

Kata runtime & agent:
- [x] Sealed Secret use as env & unit test 
- [x] Sealed Secret use as volume file & unit test 
- [x] Call CDH to unseal with Ttrpc client
- [x] Kata E2E Test

Kata Rootfs 
- [x] Makefile for CDH
- [ ] put CDH to guest image as systemd service
- [ ] put CDH to guest image as initrd script
- [x] Startup order

**Comment by arronwy** [comment]
@LindaYu17 @Lu-Biao

**Comment by arronwy** [comment]
[CC | add sealed secret support in Kata](https://github.com/kata-containers/kata-containers/pull/7570#top) 
ci: Add test cases for CoCo sealed secret feature  https://github.com/kata-containers/tests/pull/5754

**Comment by arronwy** [comment]
Current CDH & AA is launched by Kata-agent to support runtime with rootfs and initrd with one code base.
