### ISSUE TITLE
Roadmap to develop Confidential DataHub

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/guest-components#296]
As proposed in https://github.com/confidential-containers/confidential-containers/issues/136, confidential datahub helps to access different resources/data. This roadmap aims to provide a roadmap to track on this. There are two main goals:
1. Bring in confidential datahub as a guest service
2. Refactor attestation-agent so that only attestation-related APIs are provided

As attestation-agent now has some important APIs like `get_resource()` etc, we will try not to break current mechanism in such a way:
1. Add KBS-client related features to CDH firstly so that the first version of CDH can replace the attestation-agent and will not break current system.
2. Do the refactoring and add more features.

#### Stage 1

- [ ] CDH repo
- [ ] KMS trait definition
- [ ] Support KBS Client to access resources from KBS
- [ ] Support GetResource API
- [ ] Support KeyProvider(Image Decryption) API
- [ ] Support Aliyun KMS client as an example implementation for KMS
- [ ] Refactor Attestation-Agent
- [ ] https://github.com/confidential-containers/guest-components/issues/295

#### Stage 2
- [ ] Tool to generate sealed secret
- [ ] Tool to sign image & sealed secret

The roadmap & task list can be updated then.

**Comment by arronwy** [comment]
@LindaYu17 @Lu-Biao
